<a href="https://colab.research.google.com/github/narchitect/Codeit-Data-Science/blob/main/codeit_datasc02_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy
array1 = numpy.array([2,3,5,7,11,13,17,19,23,29,31])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(11,)

In [7]:
array2 = numpy.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])

In [8]:
type(array2)

numpy.ndarray

In [9]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
array2.shape

(3, 4)

In [11]:
array1.size

11

In [12]:
array2.size

12

# Practice 01 
1부터 100까지(1과 100 포함) 담겨 있는 numpy array를 생성하고 출력해 주세요.

주의: 자동 채점 과제입니다. 정답 출력 코드는 print(arr)이 아닌 arr로 작성해 주세요.

In [14]:
import numpy as np

arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

# Practice 02
1 이상 100 이하의 자연수(수나 순서를 셀 때 쓰는 1, 2, 3 과 같은 수) 중 3의 배수만 담겨 있는 numpy array를 생성하고 출력해 주세요.

주의: 자동 채점 과제입니다. 정답 출력 코드는 print(arr)이 아닌 arr로 작성해 주세요.


In [16]:
import numpy as np

arr = np.arange(3, 101, 3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])